-- Reverse of 0002_app_role.sql
-- Revokes privileges and drops the stack_app role.
-- Dropping a role with grants requires REVOKE first.

REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM stack_app;
REVOKE USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public FROM stack_app;
REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM stack_app;
REVOKE USAGE ON SCHEMA public FROM stack_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM stack_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE USAGE, SELECT ON SEQUENCES FROM stack_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM stack_app;

DROP ROLE IF EXISTS stack_app;
