-- =============================================================================
-- Rollback: 0015_member_card_number
-- Description: Reverses the card_number column addition.
-- WARNING: Apply only on a Neon preview branch before staging/production.
-- =============================================================================

-- Drop the unique index before the column.
DROP INDEX IF EXISTS public.members_tenant_card_number_unique_idx;

-- Drop the column (destructive — data is lost, but column is derived from member id
-- so it can be regenerated by re-applying the migration).
ALTER TABLE public.members
  DROP COLUMN IF EXISTS card_number;
