import { pgEnum, pgTable, text, uuid } from "drizzle-orm/pg-core";
import { type Branded, createdAt, tenantIdColumn } from "./_shared";
import { chatThreads } from "./chat-threads";

export type ChatMessageId = Branded<string, "ChatMessageId">;

/**
 * chat_message_role — the speaker in a conversation turn.
 *
 * user:      message sent by the library member.
 * assistant: response generated by the Reader's Advisor AI.
 */
export const chatMessageRoleEnum = pgEnum("chat_message_role", ["user", "assistant"]);

/**
 * chat_messages — individual turns within a chat thread.
 *
 * Multi-tenancy: tenant_id set from verified JWT org via withTenantTx.
 * RLS FORCE + assert_tenant() policy enforced by migration 0009.
 *
 * thread_id FK with ON DELETE CASCADE: removing a thread removes all its messages.
 *
 * book_ids: UUIDs extracted from assistant messages that contain <book:UUID> tokens.
 *   Populated by the route handler onFinish callback (Spec 06 Builder D).
 *   Nullable — user messages and refusals have no book references.
 */
export const chatMessages = pgTable("chat_messages", {
  id: uuid("id").primaryKey().defaultRandom(),
  tenantId: tenantIdColumn(),
  threadId: uuid("thread_id")
    .notNull()
    .references(() => chatThreads.id, { onDelete: "cascade" }),
  role: chatMessageRoleEnum("role").notNull(),
  content: text("content").notNull(),
  bookIds: uuid("book_ids").array(),
  createdAt: createdAt(),
});

export type ChatMessageRow = typeof chatMessages.$inferSelect;
export type NewChatMessageRow = typeof chatMessages.$inferInsert;
