import { boolean, integer, pgEnum, pgTable, text, uuid } from "drizzle-orm/pg-core";
import { type Branded, createdAt, tenantIdColumn, updatedAt } from "./_shared";
import { members } from "./members";
import { tenants } from "./tenants";

export type EmailBatchId = Branded<string, "EmailBatchId">;

/**
 * email_batch_status — lifecycle of a librarian-composed batch email.
 *
 * sent:     all recipients dispatched without error.
 * partial:  some recipients succeeded, some failed (see outgoing_emails rows).
 * failed:   all dispatches failed or the batch was aborted.
 */
export const emailBatchStatusEnum = pgEnum("email_batch_status", ["sent", "partial", "failed"]);

/**
 * email_batches — one row per librarian-composed batch email campaign.
 *
 * Multi-tenancy: tenant_id set from verified JWT org via withTenantTx.
 * RLS ENABLE + FORCE + tenant_isolation policy enforced by migration 0010.
 *
 * created_by: the member (librarian/admin) who composed and sent the batch.
 * audience_filter: opaque filter key (e.g. "overdue_7d", "due_this_week").
 * ai_drafted: true when the draft was generated by draftPatronEmail (Spec 07 REQ-07-06).
 * recipient_count: snapshot count at send time (audience may shift after send).
 * status: terminal state of the batch dispatch.
 */
export const emailBatches = pgTable("email_batches", {
  id: uuid("id").primaryKey().defaultRandom(),
  tenantId: tenantIdColumn().references(() => tenants.id, { onDelete: "cascade" }),
  createdBy: uuid("created_by")
    .notNull()
    .references(() => members.id),
  audienceFilter: text("audience_filter").notNull(),
  subject: text("subject").notNull(),
  bodyMarkdown: text("body_markdown").notNull(),
  recipientCount: integer("recipient_count").notNull(),
  aiDrafted: boolean("ai_drafted").notNull().default(false),
  status: emailBatchStatusEnum("status").notNull(),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

export type EmailBatchRow = typeof emailBatches.$inferSelect;
export type NewEmailBatchRow = typeof emailBatches.$inferInsert;
